# Setup
title: Jerry Wang's Blog
tagline: "Jerry Wang's Blog"
description: "Jerry Wang's Blog"
url: https://szjerrywang.github.io
baseurl: ""
paginate: 5
permalink: pretty

# About/contact
author:
  name: Jerry Wang
  url: https://szjerrywang.github.io
  email: golfsoft@gmail.com

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version: 1.1.0
google_analytics_id: #UA-XXXX-Y
